### ISSUE TITLE
Disable this repository

### ISSUE THREAD

**Issue by jotego** [MiSTer-devel/Arcade-GnG_MiSTer#14]
I kindly request to have this repository disabled as it creates problems for users. This repository is not up to date with new developments in the core.

**Comment by dfilskov** [comment]
I agree - the new JTGNG is better.

**Comment by Chocobobobo** [comment]
Yes, the original author is not maintaining this fork, and neither is anyone else anyway.
Just pointless to keep anything outdated around. Just more confusing than anything else.
Thanks!

**Comment by dfilskov** [comment]
Well ... latest release was only last month - it is maintained I guess but no need to maintain two seperate forks IMO.

**Comment by jotego** [comment]
The _MiSTer framework_ in the core is maintained, but the core itself isn't. It seems to have the old bug about climbing imaginary ladders still active from what I hear.

**Comment by sorgelig** [comment]
done

**Comment by jotego** [comment]
Thank you very much, I appreciate it.
